# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-31 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'Date Updated')),
                ('approved_at', models.DateTimeField(auto_now=True, verbose_name=b'Date Approved')),
                ('approved', models.BooleanField(default=False)),
                ('activity_code', models.CharField(blank=True, max_length=4, null=True)),
                ('activity_text', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_activity_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_activity_created_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Created by')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'Date Updated')),
                ('approved_at', models.DateTimeField(auto_now=True, verbose_name=b'Date Approved')),
                ('approved', models.BooleanField(default=False)),
                ('aa', models.CharField(blank=True, max_length=4, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=64, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=64, null=True)),
                ('address_line3', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_address_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_address_created_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Created by')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'Date Updated')),
                ('approved_at', models.DateTimeField(auto_now=True, verbose_name=b'Date Approved')),
                ('approved', models.BooleanField(default=False)),
                ('alt_name', models.CharField(blank=True, max_length=32, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('maiden_name', models.CharField(blank=True, max_length=32, null=True)),
                ('degree', models.CharField(blank=True, max_length=4, null=True)),
                ('class_year', models.CharField(blank=True, max_length=4, null=True)),
                ('business_name', models.CharField(blank=True, max_length=64, null=True)),
                ('major1', models.CharField(blank=True, max_length=4, null=True)),
                ('major2', models.CharField(blank=True, max_length=4, null=True)),
                ('major3', models.CharField(blank=True, max_length=4, null=True)),
                ('masters_grad_year', models.CharField(blank=True, max_length=4, null=True)),
                ('job_title', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_alumni_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_alumni_created_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Created by')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'Date Updated')),
                ('approved_at', models.DateTimeField(auto_now=True, verbose_name=b'Date Approved')),
                ('approved', models.BooleanField(default=False)),
                ('fieldname', models.CharField(blank=True, max_length=32, null=True)),
                ('display', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_privacy_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_privacy_created_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Created by')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'Date Updated')),
                ('approved_at', models.DateTimeField(auto_now=True, verbose_name=b'Date Approved')),
                ('approved', models.BooleanField(default=False)),
                ('relation_code', models.CharField(blank=True, max_length=8, null=True)),
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_relative_updated_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_relative_created_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Created by')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'get_latest_by': 'created_at',
            },
        ),
    ]
